containerd_config: /etc/containerd/config.toml
kube_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - net-tools

kube_version: "1.35"

kube_packages:
  - kubelet={{ kube_version }}.0-1.1
  - kubeadm={{ kube_version }}.0-1.1
  - kubectl={{ kube_version }}.0-1.1