apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-issuer
  namespace: jwt-issuer
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jwt-issuer
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.key
      remoteRef:
        key: jwt-issuer
        property: root-cert
    - secretKey: token
      remoteRef:
        key: jwt-issuer
        property: token
