apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: admin_password
    remoteRef:
      key: harbor
      property: admin_password