- name: Enable kubelet restart
  systemd:
    name: kubelet
    state: restarted

- name: Set system-wide environment variable
  lineinfile:
    path: /etc/environment
    line: 'KUBECONFIG="/etc/kubernetes/admin.conf"'
    state: present
  become: true