apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup
  namespace: backup
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backup
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: proton_username
    remoteRef:
      key: backup
      property: proton_username
  - secretKey: proton_password
    remoteRef:
      key: backup
      property: proton_password
  - secretKey: proton_client_access_token
    remoteRef:
      key: backup
      property: proton_client_access_token
  - secretKey: proton_client_refresh_token
    remoteRef:
      key: backup
      property: proton_client_refresh_token
  - secretKey: proton_client_salted_key_pass
    remoteRef:
      key: backup
      property: proton_client_salted_key_pass
  - secretKey: proton_client_uid
    remoteRef:
      key: backup
      property: proton_client_uid