# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hataraki-assistant-backend
  namespace: hataraki-assistant
  labels:
    app: hataraki-assistant-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hataraki-assistant-backend
  template:
    metadata:
      labels:
        app: hataraki-assistant-backend
    spec:
      imagePullSecrets:
        - name: docker-pull-secret
      containers:
        - name: mcp-server
          image: harbor.hatarakiassistant.com/docker/backend:0.5.0
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_FINANCES_SHEET
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: GOOGLE_FINANCES_SHEET
            - name: LLM_API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: LLM_API_ENDPOINT
            - name: MAIN_AGENT_MODEL
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: MAIN_AGENT_MODEL
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: MCP_API_ENDPOINT
            - name: JWT_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: JWT_ISSUER_URL
            - name: JWT_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: hataraki-assistant-config
                  key: JWT_ENABLED
            # Individual keys from Secret
            - name: LLM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: regolo-tokens
                  key: token
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-issuer
                  key: token
            - name: GOOGLE_JSON_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: json
          volumeMounts:
            - name: output
              mountPath: /app/backend/output
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: output
          emptyDir: {}
