apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-secrets
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: telegram-bot-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: bot_token
    remoteRef:
      key: telegram
      property: bot_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regolo-tokens
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: regolo-tokens
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: token
    remoteRef:
      key: regolo-llm
      property: token