apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-secrets
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: telegram-bot-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: bot_token
    remoteRef:
      key: telegram
      property: bot_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regolo-tokens
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: regolo-tokens
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: token
    remoteRef:
      key: regolo-llm
      property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-pull-secret
  namespace: hataraki-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: docker-pull-secret
    type: kubernetes.io/dockerconfigjson
    template:
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.hatarakiassistant.com/docker": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }

  data:
    - secretKey: token
      remoteRef:
        key: harbor
        property: token
    - secretKey: username
      remoteRef:
        key: harbor
        property: username
    - secretKey: registry
      remoteRef:
        key: myapp/registry
        property: registry   