apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegram-bot-secrets
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: telegram-bot-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: bot_token
    remoteRef:
      key: telegram
      property: bot_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regolo-tokens
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: regolo-tokens
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: token
    remoteRef:
      key: regolo-llm
      property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-pull-secret
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: docker-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.hatarakiassistant.com": {
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: harbor
        property: token
    - secretKey: username
      remoteRef:
        key: harbor
        property: username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-issuer
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: jwt-issuer
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: jwt-issuer
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google
  namespace: hataraki-assistant
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: google
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: json
      remoteRef:
        key: google
        property: json