apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment_telegram.yaml
  - deployment_backend.yaml
  - service_backend.yaml
  - externalsecret.yaml
  - configmap.yaml