apiVersion: v1
kind: Service
metadata:
  name: hataraki-assistant-backend
  namespace: hataraki-assistant
spec:
  selector:
    app: hataraki-assistant-backend
  ports:
    - port: 8000
      targetPort: 8000