apiVersion: v1
kind: Service
metadata:
  name: hataraki-assistant-service
  namespace: hataraki-assistant
spec:
  type: ClusterIP
  selector:
    component: hataraki-assistant-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP