- name: check systemd or cgroupfs
  command: ps -p 1 -o comm=
  register: cgroup_output

- name: Setup kubelet with systemd cgroup driver
  command: echo "System uses systemd"
  when: cgroup_output.stdout | trim == "systemd"