- name: check systemd or cgroupfs
  command: ps -p 1 -o comm=
  register: cgroup_output

- name: Setup kubelet with systemd cgroup driver
  command: echo "System uses systemd"
  when: cgroup_output.stdout | trim == "systemd"

- name: Configure kubelet to use systemd cgroup if present
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS="?(.*)"?$'
    line: 'KUBELET_EXTRA_ARGS="\1 --cgroup-driver=systemd"'
    backrefs: yes
    create: yes
    owner: root
    group: root
    mode: '0644'
  when: cgroup_output.stdout | trim == "systemd"

- name: Configure kubelet to use cgroupfs cgroup if present
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS="?(.*)"?$'
    line: 'KUBELET_EXTRA_ARGS="\1 --cgroup-driver=cgroupfs"'
    backrefs: yes
    create: yes
    owner: root
    group: root
    mode: '0644'
  when: cgroup_output.stdout | trim == "cgroupfs"