- name: Ensure prerequisites for apt
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Create Docker keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker apt repository
  copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_lsb.codename }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install only containerd.io
  apt:
    name: containerd.io
    state: present

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Get containerd version
  shell: "containerd --version"
  register: containerd_version

- name: Set systemd_cgroup variable based on rev output
  set_fact:
    containerd_plugin_suffix: "{{ 'grpc.v1.cri' if 'v1.' in containerd_version.stdout else 'cri.v1.runtime' }}"

- name: Deploy containerd config from template
  template:
    src: containerd_config_template.toml
    dest: "{{ containerd_config }}"
    owner: root
    group: root
    mode: '0644'