- name: Set sysctl params
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: net.bridge.bridge-nf-call-iptables, value: 1 } # No skip ip tables on bridge traffic
    - { key: net.ipv4.ip_forward, value: 1 } # Enable IPv4 forwarding