- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies for Kubernetes
  apt:
    name: "{{ kube_dependencies }}"
    state: present

- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Download Kubernetes GPG key and dearmor
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /"
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name: "{{ kube_packages }}"
    state: present

- name: check systemd or cgroupfs
  command: ps -p 1 -o comm=
  register: cgroup_output

- name: Setup kubelet with systemd cgroup driver
  command: echo "System uses systemd"
  when: cgroup_output.stdout | trim == "systemd"

- name: Configure kubelet extra args
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS="--cgroup-driver=systemd --fail-swap-on=false"
    owner: root
    group: root
    mode: '0644'
  when: cgroup_output.stdout | trim == "systemd"

- name: Configure kubelet extra args
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS="--cgroup-driver=cgroupfs --fail-swap-on=false"
    owner: root
    group: root
    mode: '0644'
  when: cgroup_output.stdout | trim == "cgroupfs"