- name: Enable kubelet service (do not start or restart)
  systemd:
    name: kubelet
    enabled: yes
    daemon_reload: yes

- name: Set system-wide environment variable
  lineinfile:
    path: /etc/environment
    line: 'KUBECONFIG="/etc/kubernetes/admin.conf"'
    state: present
  become: true