- name: iptables setup
  include_tasks: iptables.yaml

- name: containerd setup
  include_tasks: containerd.yaml

- name: setup kubeadm, kubelet and kubectl
  include_tasks: kube_setup.yaml

- name: cgroup setup
  include_tasks: cgroup.yaml

- name: start kubeadm, kubelet and kubectl
  include_tasks: kube_start.yaml
