- name: helm setup
  include_tasks: helm.yaml

- name: CNI
  include_tasks: cni.yaml

- name: Enable workers
  include_tasks: enable_workers.yaml

- name: Metrics server
  include_tasks: metrics.yaml

- name: Flux installation
  include_tasks: flux.yaml

- name: Cert-Manager installation
  include_tasks: cert_manager.yaml