apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - certificate.yaml

patches:
  - target:
      kind: Gateway
      name: traefik-gateway
    patch: |-
      - op: replace
        path: /spec/listeners/0/allowedRoutes/namespaces/from
        value: All
      - op: replace
        path: /spec/listeners/1/allowedRoutes/namespaces/from
        value: All
      - op: replace
        path: /spec/listeners/1/tls
        value:
          mode: Terminate
          certificateRefs:
            - kind: Secret
              name: tls-secret
              namespace: traefik
      - op: add
        path: /spec/listeners/-
        value:
          name: ssh
          port: 2222
          protocol: TCP
          allowedRoutes:
            namespaces:
              from: All