# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  namespace: tunnel
  labels:
    app: tunnel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel-service
  template:
    metadata:
      labels:
        app: tunnel-service
    spec:
      containers:
        - name: tunnel
          image: linuxserver/openssh-server:latest
          ports:
            - containerPort: 2222
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PASSWORD_ACCESS
              value: "true"
            - name: USER_NAME
              value: "admin"
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tunnel
                  key: password
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: tunnel
                  key: auth_public_key
