# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  namespace: tunnel
  labels:
    app: tunnel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel-service
  template:
    metadata:
      labels:
        app: tunnel-service
    spec:
      containers:
        - name: tunnel
          image: linuxserver/openssh-server:latest
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p /config/.ssh && chmod 700 /config/.ssh &&
              mkdir -p /config/sshd &&
              cp /tmp/sshd_config /config/sshd/sshd_config &&
              echo "${AUTH_PUBLIC_KEYS}" >> /config/.ssh/authorized_keys &&
              exec /init
          ports:
            - containerPort: 2222
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PASSWORD_ACCESS
              value: "true"
            - name: USER_NAME
              value: "admin"
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tunnel
                  key: password
            - name: AUTH_PUBLIC_KEYS
              valueFrom:
                secretKeyRef:
                  name: tunnel
                  key: auth_public_keys
          volumeMounts:
            - name: sshd-config
              mountPath: /tmp/sshd_config
              subPath: sshd_config
      volumes:
        - name: sshd-config
          configMap:
            name: sshd-config
