apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel
  namespace: tunnel
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tunnel
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: password
    remoteRef:
      key: tunnel
      property: password
  - secretKey: auth_public_keys
    remoteRef:
      key: tunnel
      property: auth_public_keys
  - secretKey: private_key
    remoteRef:
      key: tunnel
      property: private_key
  - secretKey: server_user
    remoteRef:
      key: tunnel
      property: server_user