apiVersion: v1
kind: Service
metadata:
  name: tunnel-service
  namespace: tunnel
spec:
  selector:
    app: tunnel-service
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
    - name: reverse-tunnel
      port: 2223
      targetPort: 2223