apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-config
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rclone-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        proton_username: "{{ .proton_username }}"
        proton_password: "{{ .proton_password }}"
        proton_client_uid: "{{ .proton_client_uid }}"
        proton_client_access_token: "{{ .proton_client_access_token }}"
        proton_client_refresh_token: "{{ .proton_client_refresh_token }}"
        proton_client_salted_key_pass: "{{ .proton_client_salted_key_pass }}"
  data:
  - secretKey: proton_username
    remoteRef:
      key: backup
      property: proton_username
  - secretKey: proton_password
    remoteRef:
      key: backup
      property: proton_password
  - secretKey: proton_client_access_token
    remoteRef:
      key: backup
      property: proton_client_access_token
  - secretKey: proton_client_refresh_token
    remoteRef:
      key: backup
      property: proton_client_refresh_token
  - secretKey: proton_client_salted_key_pass
    remoteRef:
      key: backup
      property: proton_client_salted_key_pass
  - secretKey: proton_client_uid
    remoteRef:
      key: backup
      property: proton_client_uid