apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frps-config
  namespace: phd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: frps-config
    template:
      type: Opaque
      stringData:
        frps.toml: |
          bindPort = 7000
          auth.token = {{ .token }}
  data:
    - secretKey: token
      remoteRef:
        key: phd 
        property: reverse_proxy