apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-root-token
  namespace: vault
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vault-root-token
    creationPolicy: Owner
    template:
      type: Opaque
  
  data:
  - secretKey: root
    remoteRef:
      key: vault
      property: root