apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: caregiver
  namespace: caregiver
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: caregiver
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: json
      remoteRef:
        key: google
        property: json
    - secretKey: client_id
      remoteRef:
        key: google
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: google
        property: client_secret